### PR TITLE
Re-apply changes to use hodgepodge for icon management

### PR DESCRIPTION
**Pull request by JustinLove**
Revert "Revert "Merge pull request #537 from JustinLove/hodgepodge-icon-manager""

This reverts commit ded26cce598346159cca04374b31e883a30f0c4b.

### CODE REVIEW

**Comment by Quitch** [comment]
Waiting on mikey to sort out dependency handling before merging.

**Comment by Quitch** [comment]
Given that mikey has left I'm not sure that's ever going to happen. We might just have to bite the support bullet on this one and spam "ENABLE HODGEPODGE!" everywhere.

**Comment by JustinLove** [comment]
Could add a message to client mod. Not sure if enough of CMM is loaded by default to actually install it.

**Comment by Quitch** [comment]
I know we detect missing client mod, so maybe we can detect a missing server mod too

**Comment by JustinLove** [comment]
Building off that check would be a little easier.

**Pull request merged**
