### PR TITLE
Tidy up json_format.py

### PR DESCRIPTION
**Pull request by domdom**
Clean up formatting. Best to look at this one commit at a time!

### CODE REVIEW

**Review by Quitch — COMMENTED** [review]
Can you clean up the headers coming from the scripts so that they have a line space around them? This is to make finding the breaks between scripts easier if they start producing output.

Do we need PA_MEDIA_DIR importing? The format only seems to work on Legion files, so it doesn't appear to leave the local directory.

**Comment by Quitch** [comment]
Also the AI formatter is such an improvement over the old one I think I shed a tear

**Comment by Quitch** [comment]
One request for `format_ai.py` is that in the AI files `string0` appears after `compare0` unless `string1` is in the same object, in which case `string0` appears before `compare0`. Can we add logic for that scenario?

**Comment by Quitch** [comment]
I don't think we need to keep the format scripts anymore, right?

**Comment by domdom** [comment]
We don't need them anymore, no. 

I would recommend just moving it into some 'utils' folder instead of just deleting it though.

**Comment by domdom** [comment]
How about we merge this as is, and then I clean that up along with the restructure into the new layout?

**Pull request merged**
