### PR TITLE
Improve strategic icon consistency and clarity

### PR DESCRIPTION
**Pull request by quildtide**
# Pull Request Template

## Validation

- [x] I have followed the requirements of the Contributing document.
- [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have successfully tested my changes locally.
- [x] I have made corresponding changes to the documentation
- [x] I have checked my changes generate no new warnings including when `install_devel.py` is run

## What does the change do?

Uncorrupt several strategic icons, specifically:

- Fix energy icon used for Power Catalyst, Advanced Power Catalyst, and Omnisilo Storage
- Fix metal icon used for Omnisilo Storage
- Fix radar icons used by T1 Radar and Overseer
- Replace Bot/Vehicle symbols in Starcannon with Walker/Armour symbols
- Make Ripple, Tsunami, Shredder, and Archer icons follow vanilla conventions.
- Horizontally center all of the above (most of the them were off-center by a pixel).

## Why should it be included?

The current icons look much worse once you look at a side-by-side comparison. Their inconsistency and corruption cannot be unseen.

----

If  you are somehow unconvinced, let us look at the particularly cursed energy symbols in Legion strat icons currently:
There are four Legion units I know of that use the energy symbol,—but, unlike MLA, where all units (except the Icarus, due to space constraints) use the same icon—the four units (Power Catalyst, Advanced Power Catalyst, Omnisilo Storage, and Rig) all use different symbols (why?). The Rig actually uses the same symbol as MLA, while the other three units all have their own variations that look incredibly cursed once you compare them to how they *could* have looked.

The Omnisilo Storage mysteriously uses an uglier variation of the metal symbol; in contrast, the Jig and Rig both use a symbol that happens to fit perfectly inside the holes of Metal Extractors (and Mass Extractors!).

The T1 Radar and Overseer each use their own non-standard variation of the radar symbol.

The Armour and Walker Foundries have their correct symbols, but the Starcannon uses the Bot and Vehicle symbols instead.

The Ripple, Tsunami, Shredder, and Archer use a non-standard variation of their targeting symbols; this is incredibly unnecessary.

## How has this been tested?

Sandbox. Everything works when no other server mods are on. Testing with S17 + 2W caused the Shredder and Archer SIs to revert to the old ones for some reason (this persisted over several reinstallations and client restarts) for reasons beyond my understanding, but this is probably a non-issue as things work fine when other mods aren't on.

### CODE REVIEW

**Comment by quildtide** [comment]
There is nothing to comment or document.

**Comment by Quitch** [comment]
Fails to meet all validation criteria. Please comment once completed.

**Comment by quildtide** [comment]
Documentations has been changed and code has been commented.

**Comment by Quitch** [comment]
The title says this is a fix for corrupt icons, but the description positions this as a cosmetic and consistency improvement. Please clarify and provide a couple of before/after screenshots to demonstrate.

**Comment by quildtide** [comment]
It is indeed almost completely for cosmetic/consistency reasons.

Most of the changes are well-observed in https://github.com/Legion-Expansion/Legion-Expansion/pull/602/files. I believe that the primary changes are noticeable without magnification.

One of the less visible changes is how all instances of `#FFF1000` were replaced with `#FFFF00` in the T1 Radar icon.

For that, a 16x zoom may better expose what has changed:

Old:
image

New:
image

**Comment by quildtide** [comment]
I have come to realize that you probably wanted in-game screenshots.

Here is the after screenshot, with all of the changed units, oftentimes posed near their MLA counterparts for contrast and comparison:

image

I was specifically careful to make sure that the Shredder and Archer remained distinguishable from each other.

**Comment by quildtide** [comment]
image

A vaguely similar (but not identical) scene from before

**Review by Quitch — APPROVED** [review]

**Pull request merged**
